spring.application.name=ReminderServer

spring.datasource.url=jdbc:mysql://localhost:3306/reminder_ecosystem
spring.datasource.username=jai
spring.datasource.password=m416666#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configurations
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000